import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        
        
    <script src="https://cdn.botpress.cloud/webchat/v3.3/inject.js"
    strategy="afterInteractive" ></script>
<script src="https://files.bpcontent.cloud/2025/10/27/10/20251027104237-PXGM6OB0.js" 
defer
strategy="afterInteractive"></script>
    

        strategy="afterInteractive"
      </body>
    </html>
  );
}